name: gmt
description: Get current datetime in GMT from internet (example.com, google.com or your own urls) and return DateTime in UTC.
version: 0.3.1
homepage: https://github.com/vursin/gmt

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  universal_io: ^2.0.4
 
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1