name: gmt
description: Get current datetime in GMT from internet (example.com, google.com or your own urls) and return DateTime in UTC.
version: 0.7.1
homepage: https://github.com/vnniz/gmt

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
