name: gmt
description: Get current datetime in GMT from internet (example.com, google.com or your own urls) and return DateTime in UTC.
version: 0.6.0
homepage: https://github.com/vnniz/gmt

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.6
  universal_io: ^2.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
