name: gmt
description: Get current datetime in GMT from internet (example.com, google.com or your own urls) and return DateTime in UTC.
version: 0.8.0
homepage: https://github.com/lamnhan066/gmt

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.2

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
